package io.github.nodyssey.guard

import java.io.File

/**
 * The shared plumbing of the source-guard tests beside this file.
 *
 * These tests read the repository's own sources off disk, which is unusual enough to deserve its
 * rules being written down once:
 *
 * - The repository root is found by walking up from the working directory to `settings.gradle.kts`,
 *   because Gradle runs a module's tests with the module directory as the working directory and an
 *   IDE may not. Walking up answers both without a system property to forget.
 * - Only the `*Main` source sets under `src` are scanned. Test sources may name whatever they test.
 * - Every scan asserts it found files. A guard that silently scans an empty directory — because a
 *   source set was renamed, say — would pass forever while guarding nothing.
 */
internal fun repositoryRoot(): File {
    var dir = File(System.getProperty("user.dir")).absoluteFile
    while (!File(dir, "settings.gradle.kts").isFile) {
        dir = dir.parentFile
            ?: error("no settings.gradle.kts above ${System.getProperty("user.dir")} — cannot locate the repository")
    }
    return dir
}

/** Every `.kt` file in the module's production source sets, sorted so failures list stably. */
internal fun productionSources(module: File): List<File> {
    val sourceSets =
        File(module, "src").listFiles { file -> file.isDirectory && file.name.endsWith("Main") }
            ?: error("no src/*Main directories under $module")
    val files =
        sourceSets
            .flatMap { sourceSet -> sourceSet.walkTopDown().filter { it.isFile && it.extension == "kt" } }
            .sortedBy { it.invariantSeparatorsPath }
    check(files.isNotEmpty()) { "no production Kotlin sources found under $module — the guard is scanning nothing" }
    return files
}

/**
 * The string literals of a Kotlin source file, with comments stripped.
 *
 * A lexer rather than a regex because this repository's comments are full of Chinese prose and, in
 * Kotlin, block comments nest — a comment opener inside a comment opens another level, a rule that
 * has already cost an afternoon here. The lexer only has to agree with itself: the baseline the guard
 * compares against was generated by this same function, so an interpolation corner case miscounted
 * the same way on both sides still ratchets correctly.
 */
internal fun stringLiterals(source: String): List<String> {
    val literals = mutableListOf<String>()
    var i = 0
    val n = source.length
    while (i < n) {
        when {
            source.startsWith("//", i) -> {
                val end = source.indexOf('\n', i)
                i = if (end == -1) n else end
            }

            source.startsWith("/*", i) -> {
                var depth = 1
                i += 2
                while (i < n && depth > 0) {
                    when {
                        source.startsWith("/*", i) -> {
                            depth++
                            i += 2
                        }

                        source.startsWith("*/", i) -> {
                            depth--
                            i += 2
                        }

                        else -> i++
                    }
                }
            }

            source.startsWith("\"\"\"", i) -> {
                val end = source.indexOf("\"\"\"", i + 3)
                val stop = if (end == -1) n else end
                literals += source.substring(i + 3, stop)
                i = if (end == -1) n else end + 3
            }

            source[i] == '"' -> {
                val builder = StringBuilder()
                var j = i + 1
                while (j < n && source[j] != '"') {
                    if (source[j] == '\\') {
                        j += 2
                        continue
                    }
                    builder.append(source[j])
                    j++
                }
                literals += builder.toString()
                i = j + 1
            }

            source[i] == '\'' -> {
                var j = i + 1
                while (j < n && source[j] != '\'') {
                    if (source[j] == '\\') {
                        j += 2
                        continue
                    }
                    j++
                }
                i = j + 1
            }

            else -> i++
        }
    }
    return literals
}

/** CJK Unified Ideographs plus Extension A — the ranges the app's Chinese copy actually uses. */
internal fun containsCjk(text: String): Boolean =
    text.any { it.code in 0x4E00..0x9FFF || it.code in 0x3400..0x4DBF }
