plugins {
    id("plaza.kmp.library")
    alias(libs.plugins.kotlin.serialization)
}

// Fixtures are HTML and text files, and they stay files — but a common test cannot read a file.
// Kotlin/Native has no classpath and no `getResourceAsStream`, so the only way one parser test runs
// on both the host JVM and a Native target is for the fixture to arrive as Kotlin source.
//
// A Gradle task rather than a script somebody remembers to re-run: the feasibility spike did this
// with a Python script, and a fixture edited without re-running it would have tested the previous
// capture while looking like it tested the new one.
abstract class GenerateFixtureSources : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val fixtures: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = fixtures.get().asFile
        val files = root.walkTopDown().filter { it.isFile }.sortedBy { it.invariantSeparatorsPath }.toList()
        val identifiers = mutableMapOf<String, String>()
        files.forEach { file -> identifierFor(file.relativeTo(root).invariantSeparatorsPath, identifiers) }

        val source =
            buildString {
                appendLine("// Generated by the `generateFixtureSources` task from `src/commonTest/resources/fixtures`.")
                appendLine("// Edit the fixture files, not this.")
                appendLine("package io.github.nodyssey.core.html")
                appendLine()
                appendLine("internal fun generatedFixture(name: String): String? =")
                appendLine("    when (name) {")
                files.forEach { file ->
                    val name = file.relativeTo(root).invariantSeparatorsPath
                    appendLine("        \"$name\" -> ${identifiers.getValue(name)}()")
                }
                appendLine("        else -> null")
                appendLine("    }")
                files.forEach { file ->
                    val name = file.relativeTo(root).invariantSeparatorsPath
                    appendLine()
                    appendLine("private fun ${identifiers.getValue(name)}(): String =")
                    appendLine("    buildString {")
                    chunk(file.readText()).forEach { part -> appendLine("        append(\"${escape(part)}\")") }
                    appendLine("    }")
                }
            }

        val output = outputDirectory.get().asFile.resolve("io/github/nodyssey/core/html/GeneratedFixtures.kt")
        output.parentFile.mkdirs()
        output.writeText(source)
    }

    private fun identifierFor(name: String, taken: MutableMap<String, String>): String {
        val words = name.split(Regex("[^A-Za-z0-9]+")).filter { it.isNotEmpty() }
        val base = "fixture" + words.joinToString("") { word -> word.replaceFirstChar { it.uppercaseChar() } }
        var candidate = base
        var suffix = 2
        while (taken.containsValue(candidate)) candidate = "$base${suffix++}"
        taken[name] = candidate
        return candidate
    }

    // A string literal is capped at 65535 *bytes* in the class file, and these captures are mostly
    // Chinese — three bytes a character. Splitting on a surrogate pair would produce two literals
    // neither of which is valid text, so the boundary walks back one character when it lands there.
    private fun chunk(text: String): List<String> {
        val parts = mutableListOf<String>()
        var start = 0
        while (start < text.length) {
            var end = minOf(start + CHUNK, text.length)
            if (end < text.length && text[end - 1].isHighSurrogate()) end--
            parts += text.substring(start, end)
            start = end
        }
        return parts
    }

    private fun escape(text: String): String =
        buildString(text.length) {
            text.forEach { character ->
                when {
                    character == '\\' -> append("\\\\")
                    character == '"' -> append("\\\"")
                    character == '$' -> append("\\$")
                    character == '\n' -> append("\\n")
                    character == '\r' -> append("\\r")
                    character == '\t' -> append("\\t")
                    character.code < 0x20 -> append("\\u" + character.code.toString(16).padStart(4, '0'))
                    else -> append(character)
                }
            }
        }

    private companion object {
        const val CHUNK = 6_000
    }
}

val generateFixtureSources =
    tasks.register<GenerateFixtureSources>("generateFixtureSources") {
        fixtures.set(layout.projectDirectory.dir("src/commonTest/resources/fixtures"))
        outputDirectory.set(layout.buildDirectory.dir("generated/fixtures/kotlin"))
    }

// Lint walks the source directories itself rather than reading them through the Kotlin source set, so
// the dependency Gradle infers for compilation does not reach it: `lintAnalyzeAndroidHostTest` and
// the model task beside it read the generated directory while nothing tells them who writes it.
//
// Matched by name because the task types are AGP internals, and through `matching` rather than
// `named` because AGP registers them after this file has been evaluated.
val lintTasksReadingGeneratedSources = setOf("lintAnalyzeAndroidHostTest", "generateAndroidHostTestLintModel")

tasks.matching { it.name in lintTasksReadingGeneratedSources }.configureEach {
    dependsOn(generateFixtureSources)
}

kotlin {
    android {
        // Neither of the two package roots this module holds — `io.github.plaza.core` and
        // `io.github.nodyssey` — owns the other, and the namespace only ever names a generated R
        // class this module has no resources to fill. Named after the module so it does not read as a
        // claim that one half is the real one.
        namespace = "io.github.plaza.shared"
    }

    sourceSets {
        commonMain.dependencies {
            // `api`: `RichNode` and `AnsiSpan` are `@Serializable` and consumers nest them inside
            // their own serializable types, so the generated serializers are part of this module's
            // surface rather than an implementation detail — the same reasoning `:core` recorded when
            // these types lived there.
            api(libs.kotlinx.serialization.json)

            // `implementation`, and it has to stay that way: no Ksoup type may appear anywhere on
            // this module's public surface. What leaves here is the domain model.
            //
            // That rule covers parameters as well as return values, which is not where the first
            // phase left things — a handful of parsers still *accepted* an `Element` or a `Document`
            // from a public method, back when the Android side was the one parsing the HTML. Phase 2
            // moved those callers in here, so the entry points that name a Ksoup type are now
            // `internal` (`RichContentParser.parse`, `AnsiParser.sourceOf`, `SiteBootstrap.decodeOrNull`).
            // A public signature naming a type the consumer cannot resolve is one nobody can call:
            // either it is internal, or this line has to become `api`.
            implementation(libs.ksoup)
        }

        commonTest {
            kotlin.srcDir(generateFixtureSources)
            dependencies {
                implementation(kotlin("test"))
            }
        }

        // Two tests cannot be common, and both on purpose: `WebUrlTest` and `NodeSeekSiteEncodingTest`
        // are differential tests against `java.net.URI` and `java.net.URLEncoder`. What they preserve
        // is not a specification but the answers those two gave, so the JVM has to be in the room.
        androidHostTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}
